spring:
  application:
    name: solveza-api
  datasource:
    url: jdbc:postgresql://localhost:5432/solveza_api
    username: ${DB_USERNAME:solveza}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-migration-naming: true
  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.shinkaji.solveza.api.**.infrastructure.mapper.dto
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  level:
    root: WARN
    com.shinkaji.solveza.api: INFO
    org.springframework.boot: INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
